#!/bin/bash

APP="sshServersIndicator"
PREFIX="/usr"
EXE="sshServersIndicator.py"

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

echo "Installing files"

if [ ! -d "$PREFIX/share/$APP" ];then 
 mkdir "$PREFIX/share/$APP"
fi

eval cp "$DIR/*" "$PREFIX/share/$APP"

echo "Installing shorcuts"
ln -s "$PREFIX/share/$APP/$EXE" "$PREFIX/bin/$APP" 

cat "$DIR/app.desktop" | sed "s@{EXEC}@$APP@g" > "$PREFIX/share/applications/$APP.desktop"
chmod +x "$PREFIX/share/applications/$APP.desktop"
